/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function findMatched(patterns: Array<string>, haystack: string): Array<string>
export function replaceAllStream(patterns: Array<string>, replaceWith: Array<string>, rdr: string): string
